Issue 2 view an entry
DreSean-Sutton/code-journal-old pull request #6
Opened 2021-11-11 06:13 UTC by DreSean-Sutton

![code-journal-feature-2](https://user-images.githubusercontent.com/90172283/141247257-38300ccb-ab6a-44e1-9919-9d3389ad5260.gif)

2021-11-11 17:10 UTC, codingcodymiller requested changes
Hey Dre Sean! A few things:

1. Your "No entries have been recorded" element doesn't match the styling of the example, it is left-aligned and bold, and the wrong font.
2. The font used in your header is different than the example
3. Once an entry has been added, the "No Entries have been recorded" message needs to no longer be visible.
4. When you go to resubmit, make sure your new gif shows that the user stays on the same view they were last on when the page reloads.

2021-11-11 20:33 UTC, DreSean-Sutton commented
![code-journal-feature-2 v2](https://user-images.githubusercontent.com/90172283/141365116-3768f590-daf9-45b9-b384-e115a79d9e73.gif)

2021-11-11 23:46 UTC, DreSean-Sutton commented
![code-journal-feature-2 v4](https://user-images.githubusercontent.com/90172283/141384763-437aeaa0-2eb8-4552-9ca4-e363422b3e39.gif)

2021-11-12 03:00 UTC, codingcodymiller requested changes
Hey Dre Sean! It looks like in your gif if you are on the entry form view and refresh, you are sent to the entries view :thinking_face:. No matter what view the user is on when they refresh or revisit the app, they should be on the last view they were previously on.

2021-11-12 05:02 UTC, DreSean-Sutton commented
![code-journal-feature-2 v5](https://user-images.githubusercontent.com/90172283/141412636-fd128fac-4ffc-4462-acdb-52a18a7d4ba3.gif)

2021-11-12 17:03 UTC, codingcodymiller requested changes

2021-11-12 17:03 UTC, codingcodymiller commented on js/main.js
> +  }
Why is this here?

2021-11-12 17:03 UTC, codingcodymiller commented on js/main.js
> +  if ((data.view === 'entry-form') && (data.entries.length === 0)) {
Why would we switch to the entries view if `data.view` is `"entry-form"`?

2021-11-12 17:03 UTC, codingcodymiller commented on js/main.js
> +  var $dataEntriesIndex = data.entries[i];
Where is this coming from? I don't see a loop, where is `i` being sourced from? You shouldn't do it this way, you should make this function take a parameter named `entry` and when you call the function, you should be passing in a single entry object as the argument, and the function should use the values stored in that entry object as the value to generate the DOM tree.

2021-11-12 17:03 UTC, codingcodymiller commented on js/main.js
> +  $DOMPhotoColumn.className = 'column-full column-half';
Again, what is the purpose of this? You shouldn't be doing view swapping in the function to generate a DOM tree, those a completely unrelated actions

2021-11-13 01:03 UTC, DreSean-Sutton commented
![code-journal-feature-2 v6](https://user-images.githubusercontent.com/90172283/141599775-a96aa7b1-364e-44f5-affe-531398571e62.gif)

2021-11-13 01:08 UTC, codingcodymiller requested changes

2021-11-13 01:08 UTC, codingcodymiller commented on js/main.js
> +  return $dataViewEntries.prepend(renderEntry($formValues));
No `return` is necessary here, event handlers don't include return statements. You can just remove the `return` keyword and keep the work.

2021-11-13 01:08 UTC, codingcodymiller commented on js/main.js
> +function PleaseStayOnSamePageWhenRefresh() {
LOL!!! Rename this to something professional 😂

2021-11-13 01:08 UTC, codingcodymiller commented on js/main.js
> +      noEntries();
You can do this above the loop, it only needs to be done once.

2021-11-13 01:28 UTC, codingcodymiller approved these changes

2021-11-13 01:36 UTC, merged